spring.application.name=rdv-service
spring.config.import=optional:configserver:http://localhost:9999

server.port= 8083
spring.datasource.url=jdbc:mysql://localhost:1333/rdv?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
